before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - goos:
      - linux
    goarch:
      - amd64
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
archives:
- id: vke-agent-archive
  name_template: |-
    {{ if .Tag }}
    vke-agent_{{.Tag}}_{{.Os}}_{{.Arch}}
    {{ else }}
    vke-agent_vdev_{{.Os}}_{{.Arch}}
    {{ end }}
  builds:
    - vke-agent
  files: ["LICENSE","config.yaml","k8s-cluster-autoscaler.yml","k8s-helmchart-for-cloud-provider.yml","k8s-cinder-for-storage.yml", "k8s-vke-cluster-agent.yml", "k8s-rke2-canal-config.yml"]