{{ range . }}
token: {{ .Token }}
tls-san:
  - {{ .TlsSan }}
node-name: {{ .NodeName }}
{{ if .Initialize }}{{ else }}server: https://{{.ServerAddress}}:9345{{ end }}
{{ if (eq .Rke2AgentType "server") }}node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
{{ if and (eq .Rke2AgentType "agent") .Rke2NodeTaints }}node-taint:
  {{- range $item := .Rke2NodeTaints }}
  - {{ $item }}
  {{- end }}
{{ else }}{{ end }}
{{ if and (eq .Rke2AgentType "agent") .Rke2NodeLabel }}node-label:
  {{- range $item := .Rke2NodeLabel }}
  - {{ $item }}
  {{- end }}
{{ else }}{{ end }}
{{ end }}
cloud-provider-name: external
disable-cloud-controller: true