{{ range . }}
token: {{ .Token }}
tls-san:
  - {{ .TlsSan }}
node-name: {{ .NodeName }}
{{ if .Initialize }}{{ else }}server: https://{{.ServerAddress}}:9345{{ end }}
{{ if (eq .Rke2AgentType "server") }}node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
{{ else }}{{ end }}
{{ end }}
disable:
  - cloud-controller