{{ range . }}
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: vke-cluster-agent
  namespace: kube-system
spec:
  chart: https://github.com/vmindtech/vke-cluster-agent/releases/download/vke-cluster-agent-{{.ClusterAgentVersion}}/vke-cluster-agent-{{.ClusterAgentVersion}}.tgz
  targetNamespace: kube-system
  bootstrap: true
  valuesContent: |-
    serviceAccount:
      create: true
      automount: true
      name: "vke-cluster-agent"
    image:
      tag: "v{{.ClusterAgentVersion}}"
      pullPolicy: "IfNotPresent"
    environments:
      ENV: "production"
      APP_NAME: "vke-cluster-agent"
      VERSION: "v{{.ClusterAgentVersion}}"
      VKE_CLUSTER_ID: "{{.RKE2ClusterUUID}}"
      VKE_PROJECT_ID: "{{.RKE2ClusterProjectUUID}}"
      VKE_IDENTITY_URL: "{{.VkeCloudAuthURL}}"
      VKE_APPLICATION_CREDENTIAL_ID: "{{.ApplicationCredentialID}}"
      VKE_APPLICATION_CREDENTIAL_SECRET: "{{.ApplicationCredentialKey}}"
{{ end }}