{{ range .}}
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cloud-provider-vke
  namespace: kube-system
spec:
  chart: https://github.com/vmindtech/cloud-provider-vke/releases/download/vke-cloud-controller-manager-{{.CloudControllerManagerVersion}}/vke-cloud-controller-manager-{{.CloudControllerManagerVersion}}.tgz
  targetNamespace: kube-system
  bootstrap: true
  set:
   cloudConfig.global.auth-url: "{{.AuthURL}}"
   cloudConfig.global.application-credential-id: "{{.ApplicationCredentialID}}"
   cloudConfig.global.application-credential-secret: "{{.ApplicationCredentialSecret}}"
   cloudConfig.global.tls-insecure: "yes"
{{ end }}