{{ range .}}
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cinder-storage-vke
  namespace: kube-system
spec:
  chart: https://github.com/vmindtech/cloud-provider-vke/releases/download/vke-cinder-csi-{{.CloudProviderVkeVersion}}/vke-cinder-csi-{{.CloudProviderVkeVersion}}.tgz
  targetNamespace: kube-system
  bootstrap: true
  valuesContent: |-
    csi:
      plugin:
        nodePlugin:
          tolerations:
          - operator: Exists
        image:
          tag: "{{.CloudProviderVkeVersion}}"
{{ end }}