{{ range . }}
token: {{ .Token }}
tls-san:
  - {{ .TlsSan }}
node-name: {{ .NodeName }}
{{ if .Initialize }}{{ else }}server: https://{{.ServerAddress}}:9345{{ end }}
{{ if (eq .Rke2AgentType "server") }}node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
{{ else }}{{ end }}
{{ end }}
{{ if .Rke2AgentType }}
{{ if (eq .Rke2AgentType "agent") && (nq .Rke2NodeLabel [])}}
node-label:
{{ .Rke2NodeLabel | toYaml | indent 2 }}
{{ else }}{{ end }}
cloud-provider-name: external
disable-cloud-controller: true
